

POST http://localhost:4000/createClient
content-Type: application/json

{
      "email": "fafame@yahoo.fr",
      "clientName":" FAFAME ",
      "firstName": "Benoit",
      "birthDay": "1990-01-02",
      "password": "fafame"

}